name: Release Workflow

on:
  release:
    types:
      - published
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Test
        run: echo $ABC
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        env:
          ABC: ${{github.ref_name}}
        uses: docker/bake-action@v4