name: Release Workflow

env:
  ABC: ${{github.ref_name}}

on:
  release:
    types:
      - published
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: latest_tag
        run: echo ${GITHUB_REF}
        
      - name: Display Latest Tag
        run: curl "https://api.github.com/repos/${{github.repository}}/tags" | jq -r '.[0].name'
      # - 
      #   name: Test
      #   run: echo "ABC=\"$ABC\"" > env.hcl
      # -
      #   name: 'Get Previous tag'
      #   id: previoustag
      #   # run: "echo \"Command result: $(ls)\""
      #   run: git fetch --tags && git describe --tags --abbrev=0
      # - 
      #   name: Test2
      #   run: echo ${{steps.previoustag.outputs}}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # -
      #   name: Build and push
      #   uses: docker/bake-action@v4
      #   with:
      #     files: env.hcl, docker-bake.hcl