name: Release Workflow

env:
  ABC: ${{github.ref_name}}

on:
  release:
    types:
      - published
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Test
        run: echo "ABC=\"$ABC\"" > env.hcl
      -
        name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/bake-action@v4
        with:
          files: env.hcl, docker-bake.hcl