name: Release Workflow

env:
  ABC: ${{github.ref_name}}

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        run: git show-ref
      # - 
      #   name: Test
      #   run: echo "ABC=\"$ABC\"" > env.hcl
      # -
      #   name: 'Get Previous tag'
      #   id: previoustag
      #   # run: "echo \"Command result: $(ls)\""
      #   run: git fetch --tags && git describe --tags --abbrev=0
      # - 
      #   name: Test2
      #   run: echo ${{steps.previoustag.outputs}}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # -
      #   name: Build and push
      #   uses: docker/bake-action@v4
      #   with:
      #     files: env.hcl, docker-bake.hcl