name: Release Workflow

env:
  ABC: ${{github.ref_name}}

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        run: echo "PREVIOUS=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))" >> $GITHUB_OUTPUT
      - name: Test
        run: |
          echo $ABC
          echo ${{steps.previoustag.outputs.PREVIOUS}}
      - 
        name: Test
        run: echo -e "ABC=\"$ABC\"\nPREVIOUS=${{steps.previoustag.outputs.PREVIOUS}}" > env.hcl
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/bake-action@v4
        with:
          files: env.hcl, docker-bake.hcl