name: Release Workflow

env:
  ABC: ${{github.ref_name}}

on:
  release:
    types:
      - published
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2